services:
  orange:
    container_name: orange1
    # image: orangedm/orange-docker-vnc:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5901:5901"
      - "6901:6901"
    volumes:
      - ./spark_v:/opt/src

